version: "3.3"

services:
  museitjupyter:
    user: root
    container_name: museitjupyter
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      - traefik
    command: "start-notebook.sh --NotebookApp.token='${TOKEN}' --NotebookApp.password='${PASSWORD}'"
#     command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

networks:
  traefik:
    external: true
